version: '3.3'
services:
  backend:
    env_file:
      - .env
    hostname: api
    build: ./api
    ports:
      - '3000:8080'
    restart: unless-stopped
    networks:
      - app-network
  database:
    image: mysql:latest
    hostname: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - .data:/var/lib/mysql
    ports:
      - ${DATABASE_PORT}:3306
    networks:
      - app-network
  frontend:
    env_file:
      - .env
    hostname: frontend
    build: ./frontend
    ports:
      - '3001:8080'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge